Repository OsmiumCoder/rapid-report, pull requests merged in 2025-02, with the labels that each got.

#157 Fixes In Review status filter and filters/sort UI not being persisted…
  app/Http/Controllers/Incident/AssignedIncidentsController.php
  app/Http/Controllers/Incident/IncidentController.php
  app/Http/Controllers/Incident/OwnedIncidentsController.php
  resources/js/Pages/Incident/Index.tsx
  resources/js/Pages/Incident/Partials/IndexComponents/IndexFilter.tsx
  tests/Feature/Incident/IndexTest.php
Labels: bug, frontend

#159 Investigation Aggregate Root and Store Route
  app/Aggregates/InvestigationAggregateRoot.php
  app/Http/Controllers/Incident/IncidentController.php
  app/Http/Controllers/Investigation/InvestigationController.php
  app/Models/Incident.php
  app/Models/Investigation.php
  app/Notifications/Investigation/InvestigationSubmitted.php
  app/Policies/InvestigationPolicy.php
  app/StorableEvents/Investigation/InvestigationCreated.php
  database/factories/InvestigationFactory.php
  database/migrations/2025_02_02_200617_create_investigations_table.php
  resources/js/Pages/Incident/Partials/AdminActionComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Show.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationInformationPanel.tsx
  resources/js/types/Investigation/Investigation.ts
  resources/js/types/incident/Incident.ts
  resources/views/mail/investigation-submitted.blade.php
  tests/Feature/Incident/ShowTest.php
  tests/Feature/Investigation/CreateTest.php
  tests/Feature/Investigation/ShowTest.php
  tests/Feature/Investigation/StoreTest.php
  tests/Unit/Aggregates/InvestigationAggregateRootTest.php
  tests/Unit/Models/IncidentTest.php
  tests/Unit/Models/InvestigationTest.php
  tests/Unit/Policies/InvestigationPolicyTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationCreatedTest.php
Labels: enhancement, frontend, backend

#165 162 dashboard update & 151 Update Logos and Colors
  app/Http/Controllers/DashboardController.php
  app/Models/Incident.php
  app/Policies/DashboardPolicy.php
  app/Providers/AppServiceProvider.php
  public/favicon.ico
  public/images/upei.png
  resources/js/Components/ApplicationLogo.tsx
  resources/js/Components/Checkbox.tsx
  resources/js/Components/DangerButton.tsx
  resources/js/Components/DashboardNavBar.tsx
  resources/js/Components/DateInput.tsx
  resources/js/Components/LabeledCheckbox.tsx
  resources/js/Components/NavLink.tsx
  resources/js/Components/PrimaryButton.tsx
  resources/js/Components/ProgressBarCircle.tsx
  resources/js/Components/ResponsiveNavLink.tsx
  resources/js/Components/SecondaryButton.tsx
  resources/js/Components/SelectInput.tsx
  resources/js/Components/TextArea.tsx
  resources/js/Components/TextInput.tsx
  resources/js/Components/ToggleSwitch.tsx
  resources/js/Layouts/AuthenticatedLayout.tsx
  resources/js/Layouts/Partials/DesktopSidebar.tsx
  resources/js/Layouts/Partials/MobileSidebar.tsx
  resources/js/Layouts/Partials/NavigationDropDownItem.tsx
  resources/js/Layouts/Partials/NavigationItem.tsx
  resources/js/Layouts/Partials/NavigationItems.tsx
  resources/js/Layouts/Partials/Searchbar.tsx
  resources/js/Pages/Auth/Login.tsx
  resources/js/Pages/Auth/Register.tsx
  resources/js/Pages/Auth/VerifyEmail.tsx
  resources/js/Pages/Dashboard.tsx
  resources/js/Pages/Dashboard/AdminOverview.tsx
  resources/js/Pages/Dashboard/Partials/OverviewTable.tsx
  resources/js/Pages/Dashboard/SupervisorOverview.tsx
  resources/js/Pages/Dashboard/UserDashboard.tsx
  resources/js/Pages/Dashboard/UserManagement.tsx
  resources/js/Pages/Incident/Create.tsx
  resources/js/Pages/Incident/Created.tsx
  resources/js/Pages/Incident/Index.tsx
  resources/js/Pages/Incident/Partials/ActivityLogComponents/AddCommentForm.tsx
  resources/js/Pages/Incident/Partials/AdminActionComponents/SupervisorUpdate.tsx
  resources/js/Pages/Incident/Partials/IncidentHeader.tsx
  resources/js/Pages/Incident/Partials/IndexComponents/IndexFilter.tsx
  resources/js/Pages/Incident/Stages/AffectedPartyStage.tsx
  resources/js/Pages/Incident/Stages/AnonymousStage.tsx
  resources/js/Pages/Incident/Stages/IncidentInformationStage.tsx
  resources/js/Pages/Incident/Stages/SupervisorStage.tsx
  resources/js/Pages/Incident/Stages/VictimInformationStage.tsx
  resources/js/Pages/Incident/Stages/WitnessStage.tsx
  resources/js/Pages/Investigation/Create.tsx
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.tsx
  resources/views/app.blade.php
  resources/views/errors/404.blade.php
  routes/web.php
  tailwind.config.js
  tests/Feature/DashboardTest.php
  tests/Feature/Incident/IndexTest.php
  tests/Unit/Models/IncidentTest.php
  tests/Unit/Policies/DashboardPolicyTest.php
Labels: enhancement, frontend, backend

#164 Missing buttons
  resources/js/Pages/Auth/Login.tsx
  resources/js/Pages/Dashboard/UserDashboard.tsx
  resources/js/Pages/Incident/Created.tsx
Labels: enhancement, frontend

#168 Notification on Incident Created
  app/Mail/IncidentReceived.php
  app/Notifications/IncidentSubmitted.php
  app/StorableEvents/Incident/IncidentCreated.php
  composer.json
  composer.lock
  resources/views/mail/incident-received.blade.php
  resources/views/mail/incident-submitted.blade.php
  routes/web.php
  tests/Feature/Incident/StoreTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/StoreableEvents/Incident/IncidentCreatedTest.php
Labels: enhancement, backend

#169 Incident Investigation Form
  app/Http/Controllers/Investigation/InvestigationController.php
  bootstrap/cache/.gitignore
  resources/js/Components/Dropdown.tsx
  resources/js/Components/InputLabel.tsx
  resources/js/Components/LoadingIndicator.tsx
  resources/js/Components/Modal.tsx
  resources/js/Components/WitnessList.tsx
  resources/js/Pages/Auth/ConfirmPassword.tsx
  resources/js/Pages/Auth/ForgotPassword.tsx
  resources/js/Pages/Auth/Login.tsx
  resources/js/Pages/Auth/ResetPassword.tsx
  resources/js/Pages/Dashboard/UserDashboard.tsx
  resources/js/Pages/Incident/Create.tsx
  resources/js/Pages/Incident/Created.tsx
  resources/js/Pages/Incident/Partials/ActivityLogComponents/CommentComponents/ActionComment.tsx
  resources/js/Pages/Incident/Partials/AdminActionComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Partials/IncidentSupervisorActions.tsx
  resources/js/Pages/Incident/Partials/InformationComponents/AffectedPartyInformation.tsx
  resources/js/Pages/Incident/Partials/InformationComponents/IncidentInformation.tsx
  resources/js/Pages/Incident/Partials/InformationComponents/SupervisorInformation.tsx
  resources/js/Pages/Incident/Partials/InformationComponents/VictimInformation.tsx
  resources/js/Pages/Incident/Show.tsx
  resources/js/Pages/Incident/Stages/ReviewStage.tsx
  resources/js/Pages/Investigation/Create.tsx
  resources/js/Pages/Investigation/Partials/CreateComponents/RiskRankingModal.tsx
  resources/js/Pages/Profile/Edit.tsx
  resources/js/Pages/Profile/Partials/DeleteUserForm.tsx
  resources/js/Pages/Profile/Partials/UpdatePasswordForm.tsx
  resources/js/Pages/Welcome.tsx
  resources/js/app.tsx
  resources/js/ssr.tsx
  resources/js/types/Investigation/Investigation.ts
  resources/js/types/index.d.ts
  storage/app/.gitignore
  storage/app/private/.gitignore
  storage/app/public/.gitignore
  storage/debugbar/.gitignore
  storage/framework/.gitignore
  storage/framework/cache/.gitignore
  storage/framework/cache/data/.gitignore
  storage/framework/sessions/.gitignore
  storage/framework/testing/.gitignore
  storage/framework/views/.gitignore
  storage/logs/.gitignore
  tests/Feature/Investigation/CreateTest.php
Labels: enhancement, frontend

#170 Investigation missing fields
  .github/workflows/laravel.yml
  app/Aggregates/InvestigationAggregateRoot.php
  app/Data/InvestigationData.php
  app/Models/Investigation.php
  app/Policies/InvestigationPolicy.php
  app/StorableEvents/Investigation/InvestigationCreated.php
  database/factories/InvestigationFactory.php
  database/migrations/2025_02_02_200617_create_investigations_table.php
  resources/js/Pages/Incident/Partials/IncidentSupervisorActions.tsx
  resources/js/Pages/Investigation/Create.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationInformationPanel.tsx
  resources/js/types/Investigation/Investigation.ts
  tests/Feature/Investigation/CreateTest.php
  tests/Feature/Investigation/StoreTest.php
  tests/Unit/Aggregates/InvestigationAggregateRootTest.php
  tests/Unit/Data/InvestigationDataTest.php
  tests/Unit/Models/InvestigationTest.php
  tests/Unit/Policies/InvestigationPolicyTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationCreatedTest.php
Labels: frontend, backend

#172 Update README.md
  README.md
Labels: documentation

#182 161 notifications menu
  .env.example
  app/Http/Controllers/NotificationController.php
  app/Http/Middleware/HandleInertiaRequests.php
  app/Http/Middleware/HandleMarkingNotificationsAsRead.php
  app/Notifications/Incident/IncidentSubmitted.php
  app/Notifications/Investigation/InvestigationSubmitted.php
  app/StorableEvents/Incident/IncidentCreated.php
  app/StorableEvents/Investigation/InvestigationCreated.php
  bootstrap/app.php
  resources/js/Components/confirmationModal/ConfirmationModal.tsx
  resources/js/Components/confirmationModal/ConfirmationModalProvider.tsx
  resources/js/Layouts/Partials/NotificationComponents/NotificationActions.tsx
  resources/js/Layouts/Partials/NotificationComponents/NotificationList.tsx
  resources/js/Layouts/Partials/Notifications.tsx
  resources/js/Layouts/Partials/Searchbar.tsx
  resources/js/Layouts/Partials/TopBar.tsx
  resources/js/Pages/Incident/Partials/AdminActionComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Partials/AdminActionComponents/SupervisorUpdate.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationAdminActions.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationInformationPanel.tsx
  resources/js/Pages/Investigation/Show.tsx
  resources/js/app.tsx
  resources/js/hooks/useDismiss.tsx
  resources/js/types/incident/Incident.ts
  resources/js/types/index.d.ts
  resources/js/types/investigation/Investigation.ts
  resources/js/types/notification/Notification.ts
  resources/js/types/notification/NotificationData.ts
  routes/notifications.php
  routes/web.php
  tests/Feature/Incident/StoreTest.php
  tests/Feature/NotificationTest.php
  tests/TestCase.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/StoreableEvents/Incident/IncidentCreatedTest.php
Labels: enhancement, frontend, backend

#180 User managemenent dashboard
  .env.example
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/DashboardController.php
  app/Models/User.php
  database/factories/UserFactory.php
  database/seeders/DatabaseSeeder.php
  package-lock.json
  package.json
  resources/js/Components/DangerButton.tsx
  resources/js/Components/Pagination.tsx
  resources/js/Filters/uppercaseWordFormat.ts
  resources/js/Pages/Dashboard/UserManagement.tsx
  resources/js/Pages/Incident/Index.tsx
  tests/Feature/DashboardTest.php
  tests/Feature/Incident/AddCommentTest.php
  tests/Feature/Incident/IndexTest.php
  tests/Feature/Incident/SearchTest.php
  tests/Feature/Incident/ShowTest.php
  tests/Feature/Incident/StatusTest.php
  tests/Feature/Incident/StoreTest.php
  tests/Feature/Incident/SupervisorTest.php
  tests/Feature/Investigation/CreateTest.php
  tests/Feature/Investigation/ShowTest.php
  tests/Feature/Investigation/StoreTest.php
  tests/Feature/Report/ReportDataTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/Aggregates/InvestigationAggregateRootTest.php
  tests/Unit/Models/IncidentTest.php
  tests/Unit/Models/InvestigationTest.php
  tests/Unit/Models/UserTest.php
  tests/Unit/Policies/DashboardPolicyTest.php
  tests/Unit/Policies/IncidentPolicyTest.php
  tests/Unit/Policies/InvestigationPolicyTest.php
  tests/Unit/Policies/ReportPolicyTest.php
  tests/Unit/StoreableEvents/Incident/IncidentClosedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentCreatedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentReopenedTest.php
  tests/Unit/StoreableEvents/Incident/SupervisorAssignedTest.php
  tests/Unit/StoreableEvents/Incident/SupervisorUnassignedTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationCreatedTest.php
Labels: enhancement, frontend, backend

#181 Delete user
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/User/UserController.php
  app/Http/Controllers/User/UserRoleController.php
  app/Models/User.php
  app/Policies/UserPolicy.php
  app/StorableEvents/User/UserDeleted.php
  database/migrations/0001_01_01_000000_create_users_table.php
  database/seeders/RolesAndPermissionsSeeder.php
  resources/js/Helpers/Incident/statusUpdates.ts
  resources/js/Pages/Dashboard/UserManagement.tsx
  routes/incidents.php
  routes/users.php
  routes/web.php
  tests/Feature/DashboardTest.php
  tests/Feature/Incident/StatusTest.php
  tests/Feature/Incident/SupervisorTest.php
  tests/Feature/ProfileTest.php
  tests/Feature/User/DestroyTest.php
  tests/Unit/Policies/UserPolicyTest.php
  tests/Unit/StoreableEvents/User/UserDeletedTest.php
Labels: enhancement, frontend, backend

#183 171 apply sort on incident index column click
  resources/js/Components/DangerButton.tsx
  resources/js/Pages/Incident/Index.tsx
Labels: bug, frontend

#186 Add user on user management
  app/Http/Controllers/User/UserController.php
  app/Http/Controllers/User/UserRoleController.php
  app/Mail/UserAdded.php
  app/StorableEvents/User/UserCreated.php
  resources/js/Pages/Dashboard/Partials/AddUserForm.tsx
  resources/js/Pages/Dashboard/UserManagement.tsx
  resources/views/mail/user-added.blade.php
  routes/web.php
  tests/Feature/User/StoreTest.php
  tests/Feature/User/UserRoleTest.php
  tests/Unit/StoreableEvents/User/UserCreatedTest.php
Labels: enhancement, frontend, backend

#189 #185 - Adds hazard class calculation in investigation event
  app/Aggregates/InvestigationAggregateRoot.php
  app/Data/InvestigationData.php
  app/StorableEvents/Investigation/InvestigationCreated.php
  resources/js/Pages/Investigation/Create.tsx
  tests/Feature/Investigation/StoreTest.php
  tests/Unit/Aggregates/InvestigationAggregateRootTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationCreatedTest.php
Labels: enhancement, backend

#191 Root cause analysis store
  app/Aggregates/RootCauseAnalysisAggregateRoot.php
  app/Data/RootCauseAnalysisData.php
  app/Http/Controllers/Incident/IncidentController.php
  app/Http/Controllers/RootCauseAnalysis/RootCauseAnalysisController.php
  app/Models/Incident.php
  app/Models/RootCauseAnalysis.php
  app/Notifications/RootCauseAnalysis/RootCauseAnalysisSubmitted.php
  app/StorableEvents/Investigation/InvestigationCreated.php
  app/StorableEvents/RootCauseAnalysis/RootCauseAnalysisCreated.php
  database/factories/RootCauseAnalysisFactory.php
  database/migrations/2025_02_13_212816_create_root_cause_analyses_table.php
  resources/js/Pages/Incident/Partials/IncidentSupervisorActions.tsx
  resources/js/Pages/RootCauseAnalysis/Create.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/ExecutionOfWork.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/PersonalProtectiveEquipment.tsx
  resources/js/types/rootCauseAnalysis/RootCauseAnalysisData.ts
  resources/views/mail/root-cause-analysis-submitted.blade.php
  routes/root-cause-analyses.php
  routes/web.php
  tests/Feature/Investigation/StoreTest.php
  tests/Feature/RootCauseAnalysis/CreateTest.php
  tests/Feature/RootCauseAnalysis/StoreTest.php
  tests/Unit/Aggregates/InvestigationAggregateRootTest.php
  tests/Unit/Aggregates/RootCauseAnalysisAggregateRootTest.php
  tests/Unit/Data/RootCauseAnalysisDataTest.php
  tests/Unit/Models/RootCauseAnalysisTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationCreatedTest.php
  tests/Unit/StoreableEvents/RootCauseAnalysis/RootCauseAnalysisCreatedTest.php
Labels: enhancement, backend

#201 Various Bug Fixes
  app/Data/InvestigationData.php
  app/Data/RootCauseAnalysisData.php
  app/StorableEvents/Investigation/InvestigationCreated.php
  database/migrations/2025_02_02_200617_create_investigations_table.php
  resources/js/Components/InputError.tsx
  resources/js/Components/PrimaryButtonDivider.tsx
  resources/js/Components/RadioInput/RadioGroup.tsx
  resources/js/Filters/incidentBadgeColor.ts
  resources/js/Pages/Dashboard/UserDashboard.tsx
  resources/js/Pages/Incident/Show.tsx
  resources/js/Pages/Incident/Stages/SupervisorStage.tsx
  resources/js/Pages/Investigation/Partials/CreateComponents/Causes.tsx
  resources/js/Pages/Investigation/Partials/CreateComponents/ResultedIn.tsx
  resources/js/Pages/RootCauseAnalysis/Create.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/EffectiveSolutionsAndCorrectiveActions.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/ExecutionOfWork.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/IfDoneRightQuestions.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/IndividualsInvolved.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/PersonalProtectiveEquipment.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/RootCauses.tsx
  tests/Feature/Investigation/StoreTest.php
  tests/Unit/Data/InvestigationDataTest.php
Labels: bug, frontend

#200 Status custom sort
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/Incident/AssignedIncidentsController.php
  app/Models/Incident.php
  app/States/IncidentStatus/Assigned.php
  app/States/IncidentStatus/Closed.php
  app/States/IncidentStatus/InReview.php
  app/States/IncidentStatus/Opened.php
  app/States/IncidentStatus/Reopened.php
  resources/js/Pages/Incident/Index.tsx
  tests/Unit/Models/IncidentTest.php
Labels: enhancement, backend

#199 [BUG] Risk ranking matrix modal
  resources/js/Pages/Investigation/Partials/CreateComponents/RiskRankingModal.tsx
Labels: bug, frontend

#206 Notification URL instead of route name
  app/Notifications/Incident/IncidentSubmitted.php
  app/Notifications/Investigation/InvestigationSubmitted.php
  app/Notifications/RootCauseAnalysis/RootCauseAnalysisSubmitted.php
  resources/js/Layouts/Partials/NotificationComponents/NotificationList.tsx
  resources/js/types/notification/NotificationData.ts
Labels: bug, frontend, backend

#210 Supervisor Request Review
  app/Aggregates/IncidentAggregateRoot.php
  app/Http/Controllers/Incident/IncidentController.php
  app/Http/Controllers/Incident/IncidentStatusController.php
  app/Notifications/Incident/IncidentReviewRequest.php
  app/Policies/IncidentPolicy.php
  app/StorableEvents/Incident/IncidentReviewRequested.php
  resources/js/Pages/Incident/Partials/IncidentSupervisorActions.tsx
  resources/js/Pages/Incident/Show.tsx
  resources/views/mail/incident-review-request.blade.php
  routes/incidents.php
  tests/Feature/Incident/StatusTest.php
  tests/Feature/Investigation/StoreTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/Aggregates/InvestigationAggregateRootTest.php
  tests/Unit/Policies/IncidentPolicyTest.php
  tests/Unit/StoreableEvents/Incident/IncidentReopenedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentReviewRequestedTest.php
  tests/Unit/StoreableEvents/Incident/InvestigationReturnedTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationCreatedTest.php
Labels: enhancement, frontend, backend

#218 175 rca show
  app/Aggregates/IncidentAggregateRoot.php
  app/Http/Controllers/Incident/IncidentStatusController.php
  app/Http/Controllers/Investigation/InvestigationController.php
  app/Http/Controllers/RootCauseAnalysis/RootCauseAnalysisController.php
  app/Policies/RootCauseAnalysisPolicy.php
  app/StorableEvents/Investigation/InvestigationReturned.php
  app/StorableEvents/RootCauseAnalysis/RootCauseAnalysisReturned.php
  database/factories/RootCauseAnalysisFactory.php
  database/seeders/DatabaseSeeder.php
  resources/js/Helpers/Incident/statusUpdates.ts
  resources/js/Layouts/Partials/NotificationComponents/NotificationList.tsx
  resources/js/Layouts/Partials/TopBar.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLog.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLogComponents/AddCommentForm.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLogComponents/CommentComponents/ActionComment.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLogComponents/CommentComponents/NoteComment.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionComponents/SupervisorUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentAdminActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentHeader.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentInformationPanel.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentSupervisorActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/AffectedPartyInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/GeneralDescription.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/IncidentInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/SupervisorInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/VictimInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/WitnessInformation.tsx
  resources/js/Pages/Incident/Show.tsx
  resources/js/Pages/Incident/Stages/ReviewStage.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationAdminActions.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationInformationPanel.tsx
  resources/js/Pages/RootCauseAnalysis/Create.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/IfDoneRightQuestions.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/ShowComponents/RootCauseAnalysisAdminActions.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/ShowComponents/RootCauseAnalysisInformationPanel.tsx
  resources/js/Pages/RootCauseAnalysis/Show.tsx
  resources/js/types/incident/Incident.ts
  resources/js/types/rootCauseAnalysis/IndividualInvolved.ts
  resources/js/types/rootCauseAnalysis/RootCauseAnalysis.ts
  resources/js/types/rootCauseAnalysis/RootCauseAnalysisData.ts
  resources/js/types/rootCauseAnalysis/SolutionAndAction.ts
  routes/incidents.php
  tests/Feature/Incident/StatusTest.php
  tests/Feature/RootCauseAnalysis/ShowTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/Policies/RootCauseAnalysisPolicyTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationReturnedTest.php
  tests/Unit/StoreableEvents/RootCauseAnalysis/RootCauseAnalysisReturnedTest.php
Labels: enhancement, frontend, backend

#220 Fixes supervisors not able to provide follow up on returned incidents
  app/Http/Controllers/Incident/IncidentController.php
  app/Policies/IncidentPolicy.php
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentSupervisorActions.tsx
  resources/js/Pages/Incident/Show.tsx
  tests/Feature/Incident/AddCommentTest.php
  tests/Feature/Incident/SearchTest.php
  tests/Feature/Incident/ShowTest.php
  tests/Feature/Investigation/StoreTest.php
  tests/Feature/Report/ReportDataTest.php
  tests/Feature/RootCauseAnalysis/StoreTest.php
  tests/Unit/Aggregates/InvestigationAggregateRootTest.php
  tests/Unit/Aggregates/RootCauseAnalysisAggregateRootTest.php
  tests/Unit/Data/CommentDataTest.php
  tests/Unit/Data/RootCauseAnalysisDataTest.php
  tests/Unit/Models/CommentTest.php
  tests/Unit/Models/RootCauseAnalysisTest.php
  tests/Unit/Models/UserTest.php
  tests/Unit/Policies/IncidentPolicyTest.php
  tests/Unit/Policies/InvestigationPolicyTest.php
  tests/Unit/Policies/ReportPolicyTest.php
  tests/Unit/Policies/UserPolicyTest.php
  tests/Unit/Projectors/StoredEventProjectorTest.php
  tests/Unit/Reactors/StoredEventReactorTest.php
  tests/Unit/States/IncidentStatusStateTest.php
  tests/Unit/StoreableEvents/Comment/CommentCreatedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentCreatedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentReviewRequestedTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationCreatedTest.php
  tests/Unit/StoreableEvents/RootCauseAnalysis/RootCauseAnalysisCreatedTest.php
  tests/Unit/StoreableEvents/User/UserCreatedTest.php
  tests/Unit/StoreableEvents/User/UserDeletedTest.php
  tests/Unit/StoreableEvents/User/UserRoleUpdatedTest.php
Labels: bug, frontend, backend

#221 Null user_id on event comments
  app/StorableEvents/Comment/CommentCreated.php
  app/StorableEvents/Incident/IncidentClosed.php
  app/StorableEvents/Incident/IncidentReopened.php
  app/StorableEvents/Incident/SupervisorAssigned.php
  app/StorableEvents/Incident/SupervisorUnassigned.php
  app/StorableEvents/Investigation/InvestigationReturned.php
  app/StorableEvents/RootCauseAnalysis/RootCauseAnalysisReturned.php
  tests/Unit/StoreableEvents/Incident/IncidentClosedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentReopenedTest.php
  tests/Unit/StoreableEvents/Incident/SupervisorAssignedTest.php
  tests/Unit/StoreableEvents/Incident/SupervisorUnassignedTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationReturnedTest.php
  tests/Unit/StoreableEvents/RootCauseAnalysis/RootCauseAnalysisReturnedTest.php
Labels: bug, backend

#225 215 supervisor assigned notification
  app/Notifications/Incident/SupervisorAssignedNotification.php
  app/StorableEvents/Incident/SupervisorAssigned.php
  resources/views/mail/incident-assigned.blade.php
  routes/web.php
  tests/Feature/Incident/SupervisorTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/StoreableEvents/Incident/SupervisorAssignedTest.php
Labels: enhancement, backend

#219 Report Builder
  app/Data/ReportExportData.php
  app/Enum/IncidentType.php
  app/Enum/RoleType.php
  app/Http/Controllers/Report/ReportController.php
  composer.json
  composer.lock
  package-lock.json
  resources/js/Components/DashboardNavBar.tsx
  resources/js/Components/SelectInput.tsx
  resources/js/Filters/dateFormat.ts
  resources/js/Filters/uppercaseWordFormat.ts
  resources/js/Helpers/downloadFile.ts
  resources/js/Layouts/AuthenticatedLayout.tsx
  resources/js/Layouts/Partials/NavigationItems.tsx
  resources/js/Pages/Dashboard/Partials/AddUserForm.tsx
  resources/js/Pages/Dashboard/UserManagement.tsx
  resources/js/Pages/Incident/Create.tsx
  resources/js/Pages/Incident/Stages/AffectedPartyStage.tsx
  resources/js/Pages/Incident/Stages/IncidentInformationStage.tsx
  resources/js/Pages/Report/Index.tsx
  resources/js/Pages/Report/Partials/ReportBuilder.tsx
  resources/js/Pages/Report/Partials/ReportBuildingBlock.tsx
  resources/js/Pages/Report/Stats.tsx
  resources/js/types/report/ReportData.ts
  routes/reports.php
  tests/Feature/Report/DownloadCSVTest.php
  tests/Feature/Report/DownloadXLSXTest.php
  tests/Feature/Report/IndexTest.php
  tests/Feature/Report/StatsTest.php
  tests/Unit/Data/ReportDataTest.php
Labels: enhancement, frontend, backend

#241 226 remove super admin
  app/Data/RootCauseAnalysisData.php
  app/Enum/RolesEnum.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RolesAndPermissionsSeeder.php
  resources/js/Layouts/AuthenticatedLayout.tsx
  resources/js/Layouts/Partials/NavigationItems.tsx
  resources/js/Layouts/Partials/TopBar.tsx
  resources/js/Pages/Incident/Show.tsx
  resources/js/Pages/Investigation/Show.tsx
  resources/js/Pages/RootCauseAnalysis/Create.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/CreateComponents/EffectiveSolutionsAndCorrectiveActions.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/ShowComponents/RootCauseAnalysisInformationPanel.tsx
  resources/js/Pages/RootCauseAnalysis/Show.tsx
  resources/js/Pages/Welcome.tsx
  resources/js/types/index.d.ts
  resources/js/types/rootCauseAnalysis/SolutionAndAction.ts
  routes/web.php
  tests/Feature/DashboardTest.php
  tests/Feature/RootCauseAnalysis/StoreTest.php
  tests/Unit/Aggregates/RootCauseAnalysisAggregateRootTest.php
  tests/Unit/Data/RootCauseAnalysisDataTest.php
  tests/Unit/StoreableEvents/RootCauseAnalysis/RootCauseAnalysisCreatedTest.php
Labels: bug, enhancement, frontend, backend

#242 Adds ability for users to provide additional info on incidents
  app/Aggregates/IncidentAggregateRoot.php
  app/Http/Controllers/Incident/IncidentAdditionalInformationController.php
  app/Models/Incident.php
  app/Notifications/Incident/AdditionalInformationNotification.php
  app/Policies/IncidentPolicy.php
  app/StorableEvents/Incident/AdditionalInformation.php
  database/migrations/2025_01_10_151039_create_incidents_table.php
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/SupervisorUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentAdminActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentInformationPanel.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentUserActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/AdditionalInformation.tsx
  resources/js/Pages/Incident/Show.tsx
  resources/js/types/incident/AdditionalInformation.ts
  resources/js/types/incident/Incident.ts
  resources/views/mail/incident-additional-information.blade.php
  routes/incidents.php
  routes/web.php
  tests/Feature/Incident/AdditionalInformationTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/Policies/IncidentPolicyTest.php
  tests/Unit/StoreableEvents/Incident/AdditionalInformationTest.php
  tests/Unit/StoreableEvents/Incident/IncidentCreatedTest.php
Labels: enhancement, frontend, backend

#244 Adds ability to create user from supervisor search
  app/Http/Controllers/Incident/IncidentController.php
  app/Http/Controllers/User/UserController.php
  app/StorableEvents/User/UserCreated.php
  resources/js/Pages/Dashboard/Partials/AddUserForm.tsx
  resources/js/Pages/Dashboard/Partials/AddUserModal.tsx
  resources/js/Pages/Dashboard/UserManagement.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/SupervisorUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentAdminActions.tsx
  resources/js/Pages/Incident/Show.tsx
  tests/Feature/Incident/ShowTest.php
  tests/Feature/User/StoreTest.php
  tests/Unit/StoreableEvents/User/UserCreatedTest.php
Labels: enhancement, frontend, backend

#247 Required fields made optional on follow up forms
  app/Data/InvestigationData.php
  app/Data/RootCauseAnalysisData.php
  app/Policies/IncidentPolicy.php
  app/StorableEvents/Investigation/InvestigationCreated.php
  app/StorableEvents/RootCauseAnalysis/RootCauseAnalysisCreated.php
  database/migrations/2025_02_02_200617_create_investigations_table.php
  database/migrations/2025_02_13_212816_create_root_cause_analyses_table.php
  resources/js/Layouts/Partials/NotificationComponents/NotificationList.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationInformationPanel.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/ShowComponents/RootCauseAnalysisInformationPanel.tsx
  tests/Feature/Incident/StatusTest.php
  tests/Feature/Investigation/StoreTest.php
  tests/Feature/RootCauseAnalysis/StoreTest.php
  tests/Unit/Data/RootCauseAnalysisDataTest.php
  tests/Unit/Policies/IncidentPolicyTest.php
Labels: frontend, backend

#248 Update Incident Received Email
  app/Mail/IncidentReceived.php
  app/StorableEvents/Incident/IncidentCreated.php
  resources/views/mail/incident-received.blade.php
Labels: enhancement, frontend

#249 Incident Slugs
  app/Http/Controllers/Investigation/InvestigationController.php
  app/Http/Controllers/RootCauseAnalysis/RootCauseAnalysisController.php
  app/Models/Incident.php
  app/Providers/AppServiceProvider.php
  database/migrations/2025_01_10_151039_create_incidents_table.php
  resources/js/Helpers/Incident/statusUpdates.ts
  resources/js/Layouts/Partials/Searchbar.tsx
  resources/js/Pages/Dashboard/Partials/OverviewTable.tsx
  resources/js/Pages/Dashboard/UserDashboard.tsx
  resources/js/Pages/Incident/Index.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/SupervisorUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentHeader.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentSupervisorActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentUserActions.tsx
  resources/js/Pages/Incident/Show.tsx
  resources/js/Pages/Incident/Stages/VictimInformationStage.tsx
  resources/js/Pages/Investigation/Create.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationAdminActions.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationInformationPanel.tsx
  resources/js/Pages/RootCauseAnalysis/Create.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/ShowComponents/RootCauseAnalysisAdminActions.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/ShowComponents/RootCauseAnalysisInformationPanel.tsx
  resources/js/Pages/RootCauseAnalysis/Show.tsx
  resources/js/types/incident/Incident.ts
  tests/Unit/Models/IncidentTest.php
Labels: enhancement, frontend, backend

#252 Fixes comment notification sends to self and comment policy allowing user to send comments
  app/Notifications/Comment/CommentAdded.php
  app/Policies/IncidentPolicy.php
  app/StorableEvents/Comment/CommentCreated.php
  database/seeders/RolesAndPermissionsSeeder.php
  tests/Feature/Incident/AddCommentTest.php
  tests/Unit/Policies/IncidentPolicyTest.php
  tests/Unit/StoreableEvents/Comment/CommentCreatedTest.php
Labels: bug, backend

#256 Fixes confirmation modal z-index
  resources/js/Components/ConfirmationModal/ConfirmationModal.tsx
Labels: bug, frontend

#260 Victim information to incident information
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/VictimInformation.tsx
  resources/js/Pages/Incident/Stages/VictimInformationStage.tsx
Labels: enhancement, frontend

#257 Update README.md
  README.md
Labels: documentation

#261 Tailwind Upgrade
  resources/css/app.css
  resources/js/Components/Checkbox.tsx
  resources/js/Components/ConfirmationModal/ConfirmationModalProvider.tsx
  resources/js/Components/DangerButton.tsx
  resources/js/Components/DateInput.tsx
  resources/js/Components/Dropdown.tsx
  resources/js/Components/InputError.tsx
  resources/js/Components/LabeledCheckbox.tsx
  resources/js/Components/LoadingIndicator.tsx
  resources/js/Components/Pagination.tsx
  resources/js/Components/PrimaryButton.tsx
  resources/js/Components/PrimaryButtonDivider.tsx
  resources/js/Components/RadioInput/LabelledRadioInput.tsx
  resources/js/Components/SecondaryButton.tsx
  resources/js/Components/SelectInput.tsx
  resources/js/Components/TextArea.tsx
  resources/js/Components/TextInput.tsx
  resources/js/Components/ToggleSwitch.tsx
  resources/js/Components/WitnessList.tsx
  resources/js/Layouts/Partials/NotificationComponents/NotificationActions.tsx
  resources/js/Layouts/Partials/NotificationComponents/NotificationList.tsx
  resources/js/Layouts/Partials/Notifications.tsx
  resources/js/Layouts/Partials/Searchbar.tsx
  resources/js/Layouts/Partials/TopBar.tsx
  resources/js/Pages/Auth/Login.tsx
  resources/js/Pages/Auth/Register.tsx
  resources/js/Pages/Auth/VerifyEmail.tsx
  resources/js/Pages/Dashboard/AdminOverview.tsx
  resources/js/Pages/Dashboard/Partials/AddUserModal.tsx
  resources/js/Pages/Dashboard/Partials/OverviewTable.tsx
  resources/js/Pages/Dashboard/SupervisorOverview.tsx
  resources/js/Pages/Dashboard/UserDashboard.tsx
  resources/js/Pages/Dashboard/UserManagement.tsx
  resources/js/Pages/Incident/Create.tsx
  resources/js/Pages/Incident/Created.tsx
  resources/js/Pages/Incident/Index.tsx
  resources/js/Pages/Incident/Partials/IndexComponents/IndexFilter.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLog.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLogComponents/AddCommentForm.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLogComponents/CommentComponents/ActionComment.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLogComponents/CommentComponents/NoteComment.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/SupervisorUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentAdminActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentHeader.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentInformationPanel.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentSupervisorActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentUserActions.tsx
  resources/js/Pages/Incident/Stages/WitnessStage.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationAdminActions.tsx
  resources/js/Pages/Investigation/Partials/ShowComponents/InvestigationInformationPanel.tsx
  resources/js/Pages/Profile/Edit.tsx
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.tsx
  resources/js/Pages/Report/Index.tsx
  resources/js/Pages/Report/Partials/ReportBuilder.tsx
  resources/js/Pages/Report/Partials/ReportBuildingBlock.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/ShowComponents/RootCauseAnalysisAdminActions.tsx
  resources/js/Pages/RootCauseAnalysis/Partials/ShowComponents/RootCauseAnalysisInformationPanel.tsx
Labels: bug, frontend

#267 Fixes no null check on user causing crash
  resources/js/Components/TextInput.tsx
  resources/js/Pages/Incident/Stages/AffectedPartyStage.tsx
Labels: bug, frontend

#268 Fixes affected party stage
  resources/js/Pages/Incident/Stages/AffectedPartyStage.tsx
Labels: bug, frontend
