Repository OsmiumCoder/rapid-report, pull requests merged in 2025-03, with the labels that each got.

#271 Added Activity Log to Investigation Show and RCA Show
  app/Http/Controllers/Investigation/InvestigationController.php
  app/Http/Controllers/RootCauseAnalysis/RootCauseAnalysisController.php
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLog.tsx
  resources/js/Pages/Incident/Show.tsx
  resources/js/Pages/Investigation/Show.tsx
  resources/js/Pages/RootCauseAnalysis/Show.tsx
  tests/Feature/Investigation/ShowTest.php
  tests/Feature/RootCauseAnalysis/ShowTest.php
Labels: enhancement, frontend

#274 Fixes no gap on topbar icons for small screens
  resources/js/Layouts/Partials/TopBar.tsx
Labels: bug, frontend

#276 Centers no result text in incident search
  resources/js/Layouts/Partials/Searchbar.tsx
Labels: enhancement, frontend

#278 Fixes supervisors getting 403 on incident followup create forms
  app/Http/Controllers/DashboardController.php
  app/Policies/InvestigationPolicy.php
  app/Policies/RootCauseAnalysisPolicy.php
  resources/js/Pages/Dashboard/SupervisorOverview.tsx
  tests/Feature/DashboardTest.php
  tests/Feature/Investigation/CreateTest.php
  tests/Feature/RootCauseAnalysis/CreateTest.php
  tests/Unit/Policies/InvestigationPolicyTest.php
  tests/Unit/Policies/RootCauseAnalysisPolicyTest.php
Labels: bug, backend

#272 Notification on Incident Closed
  app/Notifications/Incident/IncidentClosedNotification.php
  app/StorableEvents/Incident/IncidentClosed.php
  resources/views/mail/incident-closed-notification.blade.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/StoreableEvents/Incident/IncidentClosedTest.php
Labels: enhancement, backend

#281 Fixes activity log taking up 2/3 of screen for supervisors
  resources/js/Pages/Investigation/Show.tsx
  resources/js/Pages/RootCauseAnalysis/Show.tsx
Labels: bug, frontend

#283 Fixes supervisor actions showing for own incidents
  resources/js/Pages/Incident/Show.tsx
Labels: bug, frontend

#284 245 file storage
  .env.example
  app/Aggregates/IncidentAggregateRoot.php
  app/Http/Controllers/Incident/IncidentController.php
  app/Http/Controllers/Incident/IncidentFileController.php
  app/Models/File.php
  app/Models/Incident.php
  app/Notifications/Incident/FilesUploadedNotification.php
  app/Policies/IncidentPolicy.php
  app/StorableEvents/Incident/AdditionalInformationAdded.php
  app/StorableEvents/Incident/FileCreated.php
  app/StorableEvents/Incident/FilesUploaded.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/filesystems.php
  database/factories/FileFactory.php
  database/migrations/2025_02_27_001642_create_files_table.php
  database/seeders/RolesAndPermissionsSeeder.php
  docker-compose.yml
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/FileUploadModal.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentSupervisorActions.tsx
  resources/js/types/file/File.ts
  resources/views/mail/files-uploaded-notification.blade.php
  routes/incidents.php
  routes/web.php
  storage/app/private/.gitignore
  tests/Feature/Incident/FileTest.php
  tests/Feature/Report/DownloadCSVTest.php
  tests/Feature/Report/DownloadXLSXTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/Models/FileTest.php
  tests/Unit/Models/IncidentTest.php
  tests/Unit/Policies/IncidentPolicyTest.php
  tests/Unit/StoreableEvents/Incident/AdditionalInformationAddedTest.php
  tests/Unit/StoreableEvents/Incident/FileCreatedTest.php
  tests/Unit/StoreableEvents/Incident/FilesUploadedTest.php
Labels: enhancement, backend

#285 Notification on Incident Reopened
  app/Notifications/Incident/IncidentReopenedNotification.php
  app/StorableEvents/Incident/IncidentReopened.php
  resources/views/mail/incident-reopened-notification.blade.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/StoreableEvents/Incident/IncidentReopenedTest.php
Labels: enhancement, backend

#287 Adds incident slug to all applicable notifications
  app/Notifications/Comment/CommentAdded.php
  app/Notifications/Incident/AdditionalInformationNotification.php
  app/Notifications/Incident/FilesUploadedNotification.php
  app/Notifications/Incident/IncidentClosedNotification.php
  app/Notifications/Incident/IncidentFollowUpOverdueNotification.php
  app/Notifications/Incident/IncidentReopenedNotification.php
  app/Notifications/Incident/IncidentReviewRequestNotification.php
  app/Notifications/Incident/IncidentSubmittedNotification.php
  app/Notifications/Incident/SupervisorAssignedNotification.php
  app/Notifications/Investigation/InvestigationReturnedNotification.php
  app/Notifications/Investigation/InvestigationSubmittedNotification.php
  app/Notifications/RootCauseAnalysis/RootCauseAnalysisSubmittedNotification.php
  app/StorableEvents/Comment/CommentCreated.php
  app/StorableEvents/Incident/AdditionalInformationAdded.php
  app/StorableEvents/Incident/FilesUploaded.php
  app/StorableEvents/Incident/IncidentClosed.php
  app/StorableEvents/Incident/IncidentCreated.php
  app/StorableEvents/Incident/IncidentReviewRequested.php
  app/StorableEvents/Incident/SupervisorAssigned.php
  resources/js/Layouts/Partials/TopBar.tsx
  resources/views/mail/comment-made.blade.php
  resources/views/mail/files-uploaded-notification.blade.php
  resources/views/mail/incident-additional-information.blade.php
  resources/views/mail/incident-assigned.blade.php
  resources/views/mail/incident-closed-notification.blade.php
  resources/views/mail/incident-follow-up-overdue-notification.blade.php
  resources/views/mail/incident-review-request.blade.php
  resources/views/mail/incident-submitted.blade.php
  resources/views/mail/investigation-submitted.blade.php
  resources/views/mail/root-cause-analysis-submitted.blade.php
  routes/web.php
  tests/Feature/Incident/AdditionalInformationTest.php
  tests/Feature/Incident/FileTest.php
  tests/Feature/Incident/StatusTest.php
  tests/Feature/Incident/SupervisorTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/StoreableEvents/Incident/AdditionalInformationAddedTest.php
  tests/Unit/StoreableEvents/Incident/FilesUploadedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentReviewRequestedTest.php
Labels: enhancement, backend

#295 Adds missing information to incident show page
  resources/js/Pages/Incident/Index.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentInformationPanel.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/AdditionalInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/AffectedPartyInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/GeneralDescription.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/IncidentInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/ReportingInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/SupervisorInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/VictimInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/WitnessInformation.tsx
Labels: enhancement, frontend

#296 closed_at timestamp now set
  .github/workflows/lint.yml
  app/StorableEvents/Incident/IncidentClosed.php
  app/StorableEvents/Incident/IncidentCreated.php
  app/StorableEvents/Incident/IncidentReopened.php
  database/migrations/2025_01_10_151039_create_incidents_table.php
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLog.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentSupervisorActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/GeneralDescription.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/IncidentInformation.tsx
  resources/js/Pages/Incident/Stages/IncidentInformationStage.tsx
  resources/js/ssr.tsx
  tests/Feature/Incident/StoreTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/StoreableEvents/Incident/IncidentClosedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentCreatedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentReopenedTest.php
Labels: bug, backend

#298 Setup production
  Dockerfile
  bootstrap/app.php
  docker-compose.prod.yml
  start-container
  supervisord.conf
Labels: enhancement

#300 Updates search bar to auto focus
  resources/js/Layouts/Partials/Searchbar.tsx
Labels: bug, frontend

#301 Bug Fixes/Minor Enhancements/Changes
  app/Http/Controllers/Incident/IncidentController.php
  resources/js/Layouts/Partials/DesktopSidebar.tsx
  resources/js/Layouts/Partials/MobileSidebar.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentInformationPanel.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentSupervisorActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/GeneralDescription.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/ReportingInformation.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/VictimInformation.tsx
  resources/js/Pages/Incident/Stages/ReviewStage.tsx
  resources/js/Pages/Incident/Stages/VictimInformationStage.tsx
  resources/js/types/file/File.ts
  tests/Feature/Incident/ShowTest.php
Labels: bug, enhancement, frontend, backend

#302 Adds workflow for deployment
  .github/workflows/deploy.yml
  .gitignore
Labels: enhancement

#304 Remove workflow-dispatch from deploy.yml
  .github/workflows/deploy.yml
Labels: bug

#297 Notification on Root Cause Analysis Returned
  app/Notifications/RootCauseAnalysis/RootCauseAnalysisReturnedNotification.php
  app/StorableEvents/Investigation/InvestigationReturned.php
  app/StorableEvents/RootCauseAnalysis/RootCauseAnalysisReturned.php
  resources/views/mail/root-cause-analysis-returned.blade.php
  tests/Feature/Incident/StatusTest.php
  tests/Unit/StoreableEvents/RootCauseAnalysis/RootCauseAnalysisReturnedTest.php
Labels: enhancement, backend

#308 Storeable Event Bug Fixes
  app/StorableEvents/Incident/AdditionalInformationAdded.php
  app/StorableEvents/Incident/FilesUploaded.php
  app/StorableEvents/Incident/IncidentClosed.php
  app/StorableEvents/Incident/IncidentReopened.php
  app/StorableEvents/Incident/IncidentReviewRequested.php
  app/StorableEvents/Incident/SupervisorAssigned.php
  app/StorableEvents/Investigation/InvestigationCreated.php
  app/StorableEvents/Investigation/InvestigationReturned.php
  app/StorableEvents/RootCauseAnalysis/RootCauseAnalysisCreated.php
  app/StorableEvents/RootCauseAnalysis/RootCauseAnalysisReturned.php
  tests/Unit/StoreableEvents/Investigation/InvestigationCreatedTest.php
  tests/Unit/StoreableEvents/RootCauseAnalysis/RootCauseAnalysisCreatedTest.php
Labels: bug, backend

#309 Adds concurrency group to deploy action
  .github/workflows/deploy.yml
Labels: enhancement, backend

#310 Create LICENSE
  LICENSE
Labels: documentation

#312 Fixes comments not wrapping
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLogComponents/CommentComponents/ActionComment.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLogComponents/CommentComponents/NoteComment.tsx
Labels: bug, frontend

#324 Fixes supervisor id null error when creating/assigning
  resources/js/Pages/Dashboard/Partials/AddUserModal.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/SupervisorUpdate.tsx
Labels: bug, frontend

#330 Inertiajs React Update
  package-lock.json
  package.json
Labels: bug, backend

#329 Adds average days open to admin dashboard
  .github/workflows/tests.yml
  app/Http/Controllers/DashboardController.php
  composer.lock
  database/seeders/DatabaseSeeder.php
  resources/js/Pages/Dashboard/AdminOverview.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/InformationComponents/ReportingInformation.tsx
  tests/Feature/DashboardTest.php
Labels: enhancement, frontend, backend

#331 Adds ability to edit incident received notification message
  app/Enum/NotificationMessageType.php
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/Notification/NotificationController.php
  app/Http/Controllers/Notification/NotificationMessageController.php
  app/Mail/IncidentReceived.php
  app/Models/NotificationMessage.php
  app/Policies/DashboardPolicy.php
  app/Policies/NotificationMessagePolicy.php
  app/Providers/AppServiceProvider.php
  database/migrations/2025_03_07_151857_create_notification_messages_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/NotificationMessageSeeder.php
  database/seeders/TestSeeder.php
  package-lock.json
  resources/js/Components/TextArea.tsx
  resources/js/Layouts/AuthenticatedLayout.tsx
  resources/js/Pages/Dashboard/Settings.tsx
  resources/js/types/notification/NotificationMessage.ts
  resources/views/mail/incident-received.blade.php
  routes/dashboard.php
  routes/notifications.php
  routes/web.php
  start-container
  tests/Feature/Notification/NotificationMessageTest.php
  tests/Feature/Notification/NotificationTest.php
  tests/TestCase.php
  tests/Unit/Policies/NotificationMessagePolicyTest.php
Labels: enhancement, frontend, backend

#328 322 allow any user to upload files
  app/Http/Controllers/Incident/IncidentController.php
  app/Http/Controllers/Incident/IncidentFileController.php
  app/Policies/IncidentPolicy.php
  composer.lock
  database/seeders/RolesAndPermissionsSeeder.php
  resources/js/Pages/Incident/Index.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/AdminActionsComponents/StatusUpdate.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentFiles.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentSupervisorActions.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentUserActions.tsx
  tests/Feature/Incident/FileTest.php
  tests/Feature/Incident/ShowTest.php
Labels: enhancement, frontend, backend

#313 Stats
  app/Data/ExportData.php
  app/Exports/IncidentsExport.php
  app/Http/Controllers/Report/ReportController.php
  database/factories/IncidentFactory.php
  database/seeders/DatabaseSeeder.php
  package-lock.json
  package.json
  resources/js/Components/LabeledCheckbox.tsx
  resources/js/Pages/Report/Partials/BarGraph.tsx
  resources/js/Pages/Report/Partials/Graph.tsx
  resources/js/Pages/Report/Partials/GraphFooter.ts
  resources/js/Pages/Report/Partials/PieGraph.tsx
  resources/js/Pages/Report/Partials/ReportBuilder.tsx
  resources/js/Pages/Report/Stats.tsx
  tests/Feature/Report/ExportCSVTest.php
  tests/Feature/Report/ExportXLSXTest.php
  tests/Feature/Report/StatsTest.php
  tests/Unit/Data/ExportDataTest.php
Labels: enhancement, frontend, backend

#325 All Fields Exportable
  app/Data/ExportData.php
  app/Exports/IncidentsExport.php
  resources/js/Pages/Report/Partials/ReportBuilder.tsx
  tests/Feature/Report/StatsTest.php
Labels: enhancement, frontend, backend

#334 Fixes stats page overflowing, minor renaming to follow convention
  app/Http/Controllers/Report/ReportController.php
  resources/js/Components/NavigationBar.tsx
  resources/js/Enums/IncidentRole.ts
  resources/js/Enums/IncidentType.ts
  resources/js/Formatters/uppercaseWordFormat.ts
  resources/js/Helpers/Incident/statusUpdates.ts
  resources/js/Helpers/Report/downloadFile.ts
  resources/js/Helpers/Report/getLocationAcronym.ts
  resources/js/Helpers/Report/getPercent.ts
  resources/js/Layouts/AuthenticatedLayout.tsx
  resources/js/Layouts/Partials/NavigationItems.tsx
  resources/js/Pages/Report/Partials/BarGraph.tsx
  resources/js/Pages/Report/Partials/Graph.tsx
  resources/js/Pages/Report/Partials/GraphFooter.ts
  resources/js/Pages/Report/Partials/PieGraph.tsx
  resources/js/Pages/Report/Partials/ReportBuilder.tsx
  resources/js/Pages/Report/Partials/colors.ts
  resources/js/Pages/Report/Stats.tsx
  tests/Feature/Report/StatsTest.php
Labels: bug, frontend, backend

#333 Change location on incident form to drop down of all UPEI buildings
  resources/js/Pages/Incident/Stages/IncidentDropDownValues.ts
  resources/js/Pages/Incident/Stages/IncidentInformationStage.tsx
Labels: enhancement, frontend

#335 Removed paperclip icon and replaced incident header
  resources/js/Pages/Incident/Partials/ShowComponents/ActivityLogComponents/AddCommentForm.tsx
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentHeader.tsx
Labels: enhancement, frontend

#340 adds register button
  resources/js/Pages/Auth/Login.tsx
Labels: enhancement, frontend

#342 341 notification messages editable
  app/Enum/NotificationMessageType.php
  app/Http/Controllers/DashboardController.php
  app/Models/NotificationMessage.php
  app/Notifications/BaseNotification.php
  app/Notifications/Comment/CommentAdded.php
  app/Notifications/Incident/AdditionalInformationNotification.php
  app/Notifications/Incident/FilesUploadedNotification.php
  app/Notifications/Incident/IncidentClosedNotification.php
  app/Notifications/Incident/IncidentFollowUpOverdueNotification.php
  app/Notifications/Incident/IncidentReopenedNotification.php
  app/Notifications/Incident/IncidentReviewRequestNotification.php
  app/Notifications/Incident/IncidentSubmittedNotification.php
  app/Notifications/Incident/SupervisorAssignedNotification.php
  app/Notifications/Investigation/InvestigationReturnedNotification.php
  app/Notifications/Investigation/InvestigationSubmittedNotification.php
  app/Notifications/RootCauseAnalysis/RootCauseAnalysisReturnedNotification.php
  app/Notifications/RootCauseAnalysis/RootCauseAnalysisSubmittedNotification.php
  app/StorableEvents/Comment/CommentCreated.php
  app/StorableEvents/Incident/AdditionalInformationAdded.php
  app/StorableEvents/Incident/FilesUploaded.php
  app/StorableEvents/Incident/IncidentClosed.php
  app/StorableEvents/Incident/IncidentCreated.php
  app/StorableEvents/Incident/IncidentReopened.php
  app/StorableEvents/Incident/IncidentReviewRequested.php
  app/StorableEvents/Incident/SupervisorAssigned.php
  app/StorableEvents/Investigation/InvestigationCreated.php
  app/StorableEvents/Investigation/InvestigationReturned.php
  app/StorableEvents/RootCauseAnalysis/RootCauseAnalysisCreated.php
  app/StorableEvents/RootCauseAnalysis/RootCauseAnalysisReturned.php
  database/migrations/2025_03_14_120507_add_data_to_notification_messages_table.php
  database/seeders/NotificationMessageSeeder.php
  resources/js/Pages/Dashboard/Settings.tsx
  resources/js/types/notification/NotificationMessage.ts
  resources/views/mail/comment-made.blade.php
  resources/views/mail/incident-additional-information.blade.php
  resources/views/mail/incident-assigned.blade.php
  tests/Feature/DashboardTest.php
  tests/Feature/Incident/FileTest.php
  tests/Feature/Incident/StatusTest.php
  tests/Feature/Incident/SupervisorTest.php
  tests/Feature/Investigation/StoreTest.php
  tests/Feature/RootCauseAnalysis/StoreTest.php
  tests/Unit/Aggregates/IncidentAggregateRootTest.php
  tests/Unit/Aggregates/InvestigationAggregateRootTest.php
  tests/Unit/Aggregates/RootCauseAnalysisAggregateRootTest.php
  tests/Unit/Notification/BaseNotificationTest.php
  tests/Unit/StoreableEvents/Incident/FilesUploadedTest.php
  tests/Unit/StoreableEvents/Incident/IncidentReviewRequestedTest.php
  tests/Unit/StoreableEvents/Investigation/InvestigationCreatedTest.php
  tests/Unit/StoreableEvents/RootCauseAnalysis/RootCauseAnalysisCreatedTest.php
Labels: enhancement, frontend, backend

#344 Adds incident recording form for admins
  app/Http/Controllers/Incident/IncidentAdminCreateController.php
  app/Http/Controllers/Incident/IncidentController.php
  app/Policies/IncidentPolicy.php
  resources/js/Pages/Dashboard/AdminOverview.tsx
  resources/js/Pages/Incident/AdminCreate.tsx
  resources/js/Pages/Incident/Stages/IncidentInformationStage.tsx
  routes/incidents.php
  tests/Feature/Incident/CreateTest.php
  tests/Feature/Incident/StoreTest.php
  tests/Unit/Policies/IncidentPolicyTest.php
Labels: enhancement, frontend, backend

#346 Socialite auth
  .env.example
  Dockerfile
  app/Http/Controllers/Auth/PasswordController.php
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/User/UserController.php
  app/Http/Requests/ProfileUpdateRequest.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  app/StorableEvents/User/UserCreated.php
  bootstrap/providers.php
  composer.json
  composer.lock
  config/services.php
  database/migrations/0001_01_01_000000_create_users_table.php
  docker-compose.prod.yml
  resources/js/Pages/Auth/Login.tsx
  resources/js/Pages/Auth/Register.tsx
  resources/js/Pages/Dashboard/Partials/AddUserModal.tsx
  resources/js/Pages/Incident/Stages/AffectedPartyStage.tsx
  resources/js/Pages/Profile/Edit.tsx
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.tsx
  routes/auth.php
  routes/web.php
  supervisord.conf
  tests/Feature/Auth/PasswordResetTest.php
  tests/Feature/Auth/PasswordUpdateTest.php
  tests/Feature/Auth/RegistrationTest.php
  tests/Feature/User/StoreTest.php
  tests/Unit/StoreableEvents/User/UserCreatedTest.php
Labels: enhancement, frontend, backend

#348 Adds dev login screen
  app/Http/Controllers/Auth/AuthenticatedSessionController.php
  resources/js/Pages/Auth/DevLogin.tsx
  resources/js/Pages/Auth/Login.tsx
  routes/auth.php
  tests/Feature/Auth/AuthenticationTest.php
Labels: enhancement, frontend, backend

#350 Fixes notification message update loading indicator duplicating
  resources/js/Pages/Dashboard/Settings.tsx
Labels: bug, frontend

#352 351 user delete cascade changes
  app/Models/Investigation.php
  app/Models/RootCauseAnalysis.php
  app/Models/User.php
  app/StorableEvents/User/UserDeleted.php
  resources/js/Pages/Incident/Partials/ShowComponents/IncidentAdminActions.tsx
  tests/Unit/Models/InvestigationTest.php
  tests/Unit/Models/RootCauseAnalysisTest.php
  tests/Unit/StoreableEvents/User/UserDeletedTest.php
Labels: bug, backend
